version: '3.9'
services:
  typoteka.account.mongo:
    image: mongo:6.0.14
    restart: always
    container_name: readme-user-management_mongoDb

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - ${MONGO_PORT}:27017

    volumes:
      - readme-user-management_data:/data/db

volumes:
  readme-user-management_data:
